- name: installing shipping
  hosts: shipping
  become: yes
  tasks:
  - name: installing
    ansible.builtin.dnf:
      name: maven 
      state: present

  - name: useradd
    ansible.builtin.shell: useradd roboshop
    ignore_errors: true
    
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download shipping app
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp/

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install
    ansible.builtin.shell: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copying file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service


  
  
  - name:  daemon-reload 
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Enable service ship
    ansible.builtin.systemd_service:
      name: shipping
      enabled: true

  - name: Start service catalogue
    ansible.builtin.service:
      name: shipping
      state: started

  - name: installing mysql
    ansible.builtin.dnf:
      name: mysql 
      state: present

  - name: Load Schema
    ansible.builtin.shell: mysql -h mysql.siddhu.xyz -uroot -pRoboShop@1 < /app/schema/shipping.sql 
    ignore_errors: true


  - name: reStart service nginx
    ansible.builtin.service:
      name: shipping
      state: restarted
  

  
  

  

  
  