- name: installing web
  hosts: web
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Enable Nginx service
    ansible.builtin.systemd_service:
      name: nginx
      enabled: true

  - name: Start service nginx
    ansible.builtin.service:
      name: nginx
      state: started

  - name: Remove file (delete file)
    ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent
    
